[package]
name = "lambda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_http = "0.8.1"
tokio = { version = "1", features = ["full"]}

[[bin]]
name = "lambda"
path = "main.rs"
